# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  legionhubapiapplication:
    image: legionhubapiapplication
    build:
      context: .
      dockerfile: src/LegionHubApi/LegionHubApi.Application/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5162:5162
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
